<?xml version="1.0" encoding="utf-8"?><Database Name="QL_THUOC" Class="dcQuanLyKho" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ESTELLA\QLT;Initial Catalog=QL_THUOC;Integrated Security=True" SettingsObjectName="FormForSql.Properties.Settings" SettingsPropertyName="QL_THUOCConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BenhNhan" Member="BenhNhans">
    <Type Name="BenhNhan">
      <Column Name="IDBN" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="BenhNhan_HoaDonXuat" Member="HoaDonXuats" ThisKey="IDBN" OtherKey="IDBN" Type="HoaDonXuat" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDonNhap" Member="ChiTietHoaDonNhaps">
    <Type Name="ChiTietHoaDonNhap">
      <Column Name="MaHDN" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDThuoc" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HoaDonNhap_ChiTietHoaDonNhap" Member="HoaDonNhap" ThisKey="MaHDN" OtherKey="MaHDN" Type="HoaDonNhap" IsForeignKey="true" />
      <Association Name="THUOC_ChiTietHoaDonNhap" Member="THUOC" ThisKey="IDThuoc" OtherKey="IDThuoc" Type="THUOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDonXuat" Member="ChiTietHoaDonXuats">
    <Type Name="ChiTietHoaDonXuat">
      <Column Name="MaHDX" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDThuoc" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Thue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonVi" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HoaDonXuat_ChiTietHoaDonXuat" Member="HoaDonXuat" ThisKey="MaHDX" OtherKey="MaHDX" Type="HoaDonXuat" IsForeignKey="true" />
      <Association Name="THUOC_ChiTietHoaDonXuat" Member="THUOC" ThisKey="IDThuoc" OtherKey="IDThuoc" Type="THUOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonViTinh" Member="DonViTinhs">
    <Type Name="DonViTinh">
      <Column Name="MaDVT" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DonViTinh_THUOC" Member="THUOCs" ThisKey="MaDVT" OtherKey="MaDVT" Type="THUOC" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonNhap" Member="HoaDonNhaps">
    <Type Name="HoaDonNhap">
      <Column Name="MaHDN" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NguoiGiao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiNhan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongTienThuoc" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TongThue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTienHD" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NgayViet" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKho" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaNPP" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HoaDonNhap_ChiTietHoaDonNhap" Member="ChiTietHoaDonNhaps" ThisKey="MaHDN" OtherKey="MaHDN" Type="ChiTietHoaDonNhap" />
      <Association Name="Kho_HoaDonNhap" Member="Kho" ThisKey="MaKho" OtherKey="MaKho" Type="Kho" IsForeignKey="true" />
      <Association Name="NhaPhanPhoi_HoaDonNhap" Member="NhaPhanPhoi" ThisKey="MaNPP" OtherKey="MaNPP" Type="NhaPhanPhoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonXuat" Member="HoaDonXuats">
    <Type Name="HoaDonXuat">
      <Column Name="MaHDX" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDBN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TongTienThuoc" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongThue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTienHD" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MaKho" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="HoaDonXuat_ChiTietHoaDonXuat" Member="ChiTietHoaDonXuats" ThisKey="MaHDX" OtherKey="MaHDX" Type="ChiTietHoaDonXuat" />
      <Association Name="BenhNhan_HoaDonXuat" Member="BenhNhan" ThisKey="IDBN" OtherKey="IDBN" Type="BenhNhan" IsForeignKey="true" />
      <Association Name="Kho_HoaDonXuat" Member="Kho" ThisKey="MaKho" OtherKey="MaKho" Type="Kho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kho" Member="Khos">
    <Type Name="Kho">
      <Column Name="MaKho" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TTKho" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DD_Kho" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MaNQL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Kho_HoaDonNhap" Member="HoaDonNhaps" ThisKey="MaKho" OtherKey="MaKho" Type="HoaDonNhap" />
      <Association Name="Kho_HoaDonXuat" Member="HoaDonXuats" ThisKey="MaKho" OtherKey="MaKho" Type="HoaDonXuat" />
      <Association Name="Kho_NhanVien" Member="NhanViens" ThisKey="MaKho" OtherKey="MaKho" Type="NhanVien" />
      <Association Name="NhanVien_Kho" Member="NhanVien" ThisKey="MaNQL" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKho" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HoTenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="NhanVien_Kho" Member="Khos" ThisKey="MaNV" OtherKey="MaNQL" Type="Kho" />
      <Association Name="Kho_NhanVien" Member="Kho" ThisKey="MaKho" OtherKey="MaKho" Type="Kho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaPhanPhoi" Member="NhaPhanPhois">
    <Type Name="NhaPhanPhoi">
      <Column Name="MaNPP" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNPP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EmaiL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaSoThue" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="NhaPhanPhoi_HoaDonNhap" Member="HoaDonNhaps" ThisKey="MaNPP" OtherKey="MaNPP" Type="HoaDonNhap" />
    </Type>
  </Table>
  <Table Name="dbo.NhaSanXuat" Member="NhaSanXuats">
    <Type Name="NhaSanXuat">
      <Column Name="MaNSX" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNSX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="NhaSanXuat_THUOC" Member="THUOCs" ThisKey="MaNSX" OtherKey="MaNSX" Type="THUOC" />
    </Type>
  </Table>
  <Table Name="dbo.NhomThuoc" Member="NhomThuocs">
    <Type Name="NhomThuoc">
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="NhomThuoc_THUOC" Member="THUOCs" ThisKey="MaNhom" OtherKey="MaNhom" Type="THUOC" />
    </Type>
  </Table>
  <Table Name="dbo.THUOC" Member="THUOCs">
    <Type Name="THUOC">
      <Column Name="IDThuoc" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguonGoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThanhPhan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HamLuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CongDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhanTacDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CachDung" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ChuY" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HanSuDung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BaoQuan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DangBaoChe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaDVT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaNSX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="THUOC_ChiTietHoaDonNhap" Member="ChiTietHoaDonNhaps" ThisKey="IDThuoc" OtherKey="IDThuoc" Type="ChiTietHoaDonNhap" />
      <Association Name="THUOC_ChiTietHoaDonXuat" Member="ChiTietHoaDonXuats" ThisKey="IDThuoc" OtherKey="IDThuoc" Type="ChiTietHoaDonXuat" />
      <Association Name="DonViTinh_THUOC" Member="DonViTinh" ThisKey="MaDVT" OtherKey="MaDVT" Type="DonViTinh" IsForeignKey="true" />
      <Association Name="NhomThuoc_THUOC" Member="NhomThuoc" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomThuoc" IsForeignKey="true" />
      <Association Name="NhaSanXuat_THUOC" Member="NhaSanXuat" ThisKey="MaNSX" OtherKey="MaNSX" Type="NhaSanXuat" IsForeignKey="true" />
    </Type>
  </Table>
</Database>